# Generated by Django 2.1.7 on 2019-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
