# Generated by Django 2.1.7 on 2019-02-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0003_auto_20190224_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
