# Generated by Django 2.1.7 on 2019-02-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0004_auto_20190225_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='state_name',
            new_name='state',
        ),
    ]
