# Generated by Django 2.1.7 on 2019-02-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0005_auto_20190225_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='state_params',
            new_name='context',
        ),
    ]
