# Generated by Django 2.1.7 on 2019-02-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0006_auto_20190225_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weight_units', models.CharField(blank=True, max_length=20, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbot.Person')),
            ],
        ),
    ]
