# Generated by Django 2.1.7 on 2019-03-15 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0007_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='comments',
        ),
    ]
