# Generated by Django 2.1.7 on 2019-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0008_auto_20190315_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealimage',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
