# Generated by Django 2.1.7 on 2019-03-20 09:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0009_mealimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('website_name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('cuisine', models.CharField(choices=[('STANDARD', 'Standard'), ('KETO', 'Keto'), ('PALEO', 'Paleo'), ('VEGETARIAN', 'Vegetarian'), ('PRIMAL', 'Primal'), ('VEGAN', 'Vegan'), ('RAW_VEGAN', 'Raw Vegan'), ('LOW_CARB', 'Low Carb')], default='STANDARD', max_length=100)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
