# Generated by Django 2.1.7 on 2019-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbot', '0011_auto_20190320_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
